fahali22a
krr-up/bibliography pull request #128
Opened 2022-05-20 20:08 UTC by jorgefandinno

2022-05-20 20:10 UTC, jorgefandinno commented
The check fails on a previous entry. Should I modify it?

2022-05-21 06:52 UTC, tortinator requested changes

2022-05-21 06:52 UTC, tortinator commented on krr.bib
> +  pages = {to appear}
Please ad also an issue to update the paper once it has appeared

2022-05-21 06:52 UTC, tortinator commented on procs.bib
> +  booktitle = {Proceedings of the Thirty-sixth National Conference on Artificial Intelligence (AAAI'21)},
```suggestion
  title = {Proceedings of the Thirty-sixth National Conference on Artificial Intelligence (AAAI'22)},
  booktitle = {Proceedings of the Thirty-sixth National Conference on Artificial Intelligence (AAAI'22)},
```

2022-05-21 06:52 UTC, tortinator commented on krr.bib
> +  author = {J. Faninno and Z. Hansen and Y. Lierler},
```suggestion
  author = {J. Fandinno and Z. Hansen and Y. Lierler},
```

2022-05-21 06:52 UTC, tortinator commented on krr.bib
> +  pages = {103712},
Wow, do they have a new page scheme...?

2022-05-21 13:14 UTC, jorgefandinno commented on krr.bib
> +  pages = {103712},
they use that for online publications previous to physical publication. should i open an issue to update?

2022-05-21 13:50 UTC, tortinator commented on krr.bib
> +  pages = {103712},
Yes, would be good

2022-05-21 13:51 UTC, tortinator approved these changes

2022-05-21 13:53 UTC, tortinator commented on krr.bib
> +  pages = {103712},
Actually, I just noticed that this is also the reason why the check failed.
@rkaminsk WHat do you think? Shall we accomodate this in teh bibfmt check?

2022-05-21 14:15 UTC, rkaminsk commented on krr.bib
> +  pages = {103712},
We could just remove the pages from the bibtex. I could also let the "to appear" though. But we should probably not use the random numbers below???

2022-05-21 14:25 UTC, tortinator commented on krr.bib
> +  pages = {103712},
Ok, I'll remove the pages field and see whether it checks out, if so, I'll merge

2022-05-21 14:43 UTC, jorgefandinno commented on krr.bib
> +  pages = {to appear}
Done

2022-05-21 14:43 UTC, jorgefandinno commented on krr.bib
> +  pages = {103712},
Issues added

2022-05-21 14:51 UTC, tortinator commented on krr.bib
> +  pages = {103712},
Actually, you may want to remove it again: The actual issue is that teh entry is already in but with a different key:

```text
@article{agcafapepevi19a,
  title = {Forgetting auxiliary atoms in forks},
  author = {F. Aguado and P. Cabalar and J. Fandinno and D. Pearce and G. P{\'e}rez and C. Vidal},
  journal = aij,
  pages = {575-601},
  volume = {275},
  year = {2019}
}
```

I now removed the entry `agcafapepevi20a` and check it it

2022-05-21 14:54 UTC, jorgefandinno commented on krr.bib
> +  title = {Forgetting auxiliary atoms in forks},
```suggestion
  title = {A polynomial reduction of forks into logic programs},
```

2022-05-21 14:54 UTC, jorgefandinno commented on krr.bib
> +  pages = {103712},
It is not a random number. It is the way AIJ suggest to cite it. Click in cite an bib in the following page

https://www.sciencedirect.com/science/article/pii/S0004370222000522

2022-05-21 14:54 UTC, rkaminsk commented
Are you aware that you can run the bibfmt script locally and that it can fix simple formatting issues? Just check the readme.

2022-05-21 14:56 UTC, tortinator commented on krr.bib
> +  title = {Forgetting auxiliary atoms in forks},
Could you checkout this path again and re-add the entry with the corrected title?

2022-05-21 14:56 UTC, jorgefandinno commented on krr.bib
> +  title = {Forgetting auxiliary atoms in forks},
Yes, I did

2022-05-21 14:57 UTC, tortinator commented
> Are you aware that you can run the bibfmt script locally and that it can fix simple formatting issues? Just check the readme.

I did and got a `+` after deleting the entry, and then I uploaded :nerd_face:

2022-05-21 15:01 UTC, jorgefandinno commented on krr.bib
> +  title = {Forgetting auxiliary atoms in forks},
> Are you aware that you can run the bibfmt script locally and that it can fix simple formatting issues? Just check the readme.
> 
> EDIT: This will make your life so much easier...

Yes, I did. I don't know what happend. Sorry for the mess

2022-05-21 15:02 UTC, jorgefandinno commented
> Are you aware that you can run the bibfmt script locally and that it can fix simple formatting issues? Just check the readme.
> 
> EDIT: This will make your life so much easier...

Yes, I did. I don't know what happend. Sorry for the mess

2022-05-21 15:12 UTC, merged