Ks/mapf entries
krr-up/bibliography pull request #132
Opened 2022-07-08 12:52 UTC by kstrauch94

I added a few mapf entries and fixed the ID for the scheduling approach from Jiri (It had the names in it instead of the last names)

2022-07-08 13:29 UTC, tortinator requested changes

2022-07-08 13:29 UTC, tortinator commented on krr.bib
> +  editor = {Hang Ma and Ivan Serina},
```suggestion
  editor = {H. Ma and I. Serina},
```
Just initials

2022-07-08 13:29 UTC, tortinator commented on krr.bib
> +  biburl = {https://dblp.org/rec/conf/socs/AchaLHB21.bib},
delete - we do not use this info

Just check the other entrie sin `krr.bib`

2022-07-08 13:29 UTC, tortinator commented on krr.bib
> +  booktitle = {Proceedings of the Fourteenth International Symposium on Combinatorial Search, {SOCS} 2021, Virtual Conference [Jinan, China], July 26-30, 2021},
Please use a crossreference!

2022-07-08 13:29 UTC, tortinator commented on krr.bib
> +  publisher = {{AAAI} Press},
chaeck for macro (aka `@string`)

2022-07-08 13:29 UTC, tortinator commented on krr.bib
> +  url = {https://ojs.aaai.org/index.php/SOCS/article/view/18546},
see above

2022-07-08 13:29 UTC, tortinator commented on krr.bib
> +  year = {2021}
see above

2022-07-08 13:29 UTC, tortinator commented on krr.bib
> +@article{chhalist2021a,
This is in proceedings, or?

2022-07-15 13:26 UTC, tortinator requested changes
Just two minor things - cheers!

2022-07-15 13:26 UTC, tortinator commented on krr.bib
> +@article{chhalist2021a,
Did you change this..?

2022-07-15 13:26 UTC, tortinator commented on krr.bib
> +  booktitle = {Proceedings of the Twenty-third International Conference on Principles and Practice of Multi-Agent Systems (PRIMA'20) },
PRIMA might be worth starting with crossrefs

2022-07-15 13:26 UTC, tortinator commented on krr.bib
> +  booktitle = {Proceedings of the Twenty-sixth IEEE International Conference on Tools with Artificial Intelligence (ICTAI'14)},
ICTAI series is already in `procs.bib` - please continue adding the 14 edition

2022-07-15 15:47 UTC, tortinator requested changes
Sorry, still a few issues

2022-07-15 15:47 UTC, tortinator commented on krr.bib
> +@article{chhalist21a,
Must be `inproceedings`

2022-07-15 15:47 UTC, tortinator commented on procs.bib
> +@proceedings{ictai14,
Is there an editor?

2022-07-15 15:47 UTC, tortinator commented on procs.bib
> +  title = {Proceedings of the Fourteenth International Symposium on Combinatorial Search (SOCS'21)},
Add `booktitle`

2022-07-16 06:49 UTC, kstrauch94 commented on procs.bib
> +@proceedings{ictai14,
I can not find an editor for this conference

2022-07-18 05:17 UTC, tortinator approved these changes

2022-07-18 05:18 UTC, tortinator commented
Hola, it seems that the checks won't go through - can you fix this? Then we're ready to merge :nerd_face:

2022-07-21 06:31 UTC, tortinator commented
Are we now ready to merge..?

2022-07-21 15:06 UTC, merged