Et/mapf
krr-up/bibliography pull request #136
Opened 2022-09-13 13:56 UTC by EtienneTignon

2022-11-02 07:14 UTC, tortinator requested changes

2022-11-02 07:14 UTC, tortinator commented on krr.bib
> +@inproceedings{salube12,
```suggestion
@inproceedings{salube12a,
```

2022-11-02 07:14 UTC, tortinator commented on procs.bib
> +  editor = {D. Borrajo and A. Felner and R. Korf and M. Likhachev and C. Linares L{\'{o}}pez and W. Ruml and N. Sturtevant},
```suggestion
  editor = {D. Borrajo and A. Felner and R. Korf and M. Likhachev and C. {Linares L{\'{o}}pez} and W. Ruml and N. Sturtevant},
```

2022-11-02 15:54 UTC, EtienneTignon commented
I committed the requested changes and checked the format locally afterward.

2022-11-03 15:13 UTC, jorgefandinno commented
I get the following error
```
You can't pop an empty literal stack for entry gekakaosscwa16a
while executing---line 1338 of file mdpi.bst
You can't pop an empty literal stack for entry liesus16a
while executing---line 1338 of file mdpi.bst
```

It also seems that bibliography commit is not up to date. May be this the reason for the errors?

2022-11-03 15:44 UTC, tortinator commented
Have you updated the submodule..?

2022-11-03 16:38 UTC, jorgefandinno commented
I think so. I do have a folder ```include/latex-class-mdpi``` with a bunch of new files.

Is that enough to be sure?

2022-11-03 18:35 UTC, tortinator commented
Sorry but have you cleaned all six files, in particular, the ones related to bibtex...?

2022-11-03 20:00 UTC, jorgefandinno commented
> Sorry but have you cleaned all six files, in particular, the ones related to bibtex...?

Yes, I even cloned the repository in a new location and get the same error.

2022-11-04 07:25 UTC, tortinator approved these changes

2022-11-04 07:27 UTC, tortinator commented
@jorgefandinno I don't know - nonetheless: What dooes this have to do with @EtienneTignon's pull request..?

2022-11-04 07:30 UTC, tortinator commented
> > Sorry but have you cleaned all six files, in particular, the ones related to bibtex...?
> 
> Yes, I even cloned the repository in a new location and get the same error.

I did the same but obtain no error ....

2022-11-04 08:05 UTC, merged