Add wolper01a (Constructing Automata from Temporal Logic Formulas).
krr-up/bibliography pull request #146
Opened 2023-02-22 11:00 UTC by namcsi

Add paper discussed in Temporal/Dynamic issues reading group.

2023-02-23 17:43 UTC, tortinator approved these changes

2023-02-23 17:43 UTC, tortinator commented on procs.bib
> +  title = {Lectures on Formal Methods and Performance Analysis: First EEF/Euro Summer School on Trends in Computer Science Berg en Dal, The Netherlands, July 3-7, 2000. Revised Lectures},
```suggestion
  title = {Lectures on Formal Methods and Performance Analysis: First EEF/Euro Summer School on Trends in Computer Science},
```

2023-02-23 17:45 UTC, tortinator commented
@namcsi , doing a cross-ref is a trade-off, eg will there be a second or more references to the volume or will the article remain the only one.
Personally, I had not used a crossref here

2023-02-24 11:01 UTC, namcsi commented
Got it, I'll create a new commit with just the article. I agree it's not clear if there will be future references to other articles in the book, so crossref is not necessary.

2023-02-24 11:23 UTC, namcsi commented
Done! Rebased on top of the changes that happened on the master branch while the pull request was open so should be ready to merge now. Now I just need an authorized user to press the button :-)

2023-02-25 15:26 UTC, tortinator requested changes

2023-02-25 15:26 UTC, tortinator commented on krr.bib
> +@article{wolper01a,
```suggestion
@article{wolper03a,
```

Isn't it published in 2003...?

2023-02-25 18:55 UTC, namcsi commented on krr.bib
> +@article{wolper01a,
Ah yes the article was published initially in 2001, and then later as part of the book which was published in 2003. I'll correct the year to 2001 since we're just doing the article.

2023-02-25 19:00 UTC, namcsi commented on krr.bib
> +@article{wolper01a,
Done! Should be all good now.

2023-02-27 11:55 UTC, tortinator approved these changes

2023-02-27 11:56 UTC, merged