Nico/configuration
krr-up/bibliography pull request #153
Opened 2023-03-27 17:45 UTC by nrueh

2023-03-27 18:17 UTC, tortinator commented
Hi @nrueh , da ist irgendwas schief gegangen... ueber 10000 changes; CI checks sind fehlgeschlagen; hast Du die Formatting Skripte laufen lassen..?

2023-03-27 18:27 UTC, nrueh commented
@tortinator jetzt sollte es gefixed sein. Hatte das Formatting skript in der tat nicht laufen lassen

2023-03-27 18:37 UTC, tortinator requested changes
Sorry for nitpicking

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +  title = {LoCo - {A} Logic for Configuration Problems},
```suggestion
  title = {{LoCo} - {A} Logic for Configuration Problems},
```

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +  author = {Markus Aschinger and Conrad Drescher and Georg Gottlob and Heribert Vollmer},
```suggestion
  author = {M. Aschinger and C. Drescher and G. Gottlob and H. Vollmer},
```

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +
das haben wir bereits, such den richtigen bibkey ...

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +H. Schreiner},
One line ...

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +LoCoCo 2011, Perugia, Italy, 12th September 2011},
no place, no date, etc - cf other entries!

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +  url = {https://doi.org/10.4204/EPTCS.65.3},
no url, just doi

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +  series = {{CEUR} Workshop Proceedings},
into procs

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +  year = {2022}
ditto - cf other entries!

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +R. Sulonen},
see above

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +and Reasoning, Proceedings of the 1st Intl. ASP'01 Workshop, 2001},
see above

2023-03-27 18:37 UTC, tortinator commented on krr.bib
> +  title = {VariSales},
```suggestion
  title = {{VariSales}},
```

2023-03-27 18:42 UTC, nrueh commented on krr.bib
> +
hm, das habe ich nicht hinzugefügt. Kann beim mergen vom master passiert sein...

2023-03-27 18:50 UTC, nrueh commented on krr.bib
> +  title = {LoCo - {A} Logic for Configuration Problems},
done

2023-03-27 18:51 UTC, nrueh commented on krr.bib
> +  author = {Markus Aschinger and Conrad Drescher and Georg Gottlob and Heribert Vollmer},
done

2023-03-27 18:52 UTC, nrueh commented on krr.bib
> +  title = {VariSales},
done

2023-03-27 18:52 UTC, nrueh commented on krr.bib
> +and Reasoning, Proceedings of the 1st Intl. ASP'01 Workshop, 2001},
Ist es so wie es jetzt ist ok?

2023-03-27 18:59 UTC, nrueh commented
@tortinator done. Schaue noch einmal bei dem einen offenen Kommentar drüber, bitte.

2023-03-28 07:29 UTC, tortinator requested changes
Almsot done :innocent:

2023-03-28 07:29 UTC, tortinator commented on krr.bib
> +
Die arxiv sind inmmer etwas speziell, und ich hoffe wir kriegen da mehr Konsistenz rein; bei den anderen haben wir noch mehr an Feldern drin

2023-03-28 07:42 UTC, tortinator requested changes
detected duplicate (by chance)

2023-03-28 07:42 UTC, tortinator commented on krr.bib
> +
```suggestion
```

Delete, it's a duplicated entry  (just fyi: the booktitle is no good)

2023-03-28 10:30 UTC, nrueh commented on krr.bib
> +
Habe mir ein paar andere Einträge angeschaut und zwei Felder `journal = {CoRR` und `volume={abs/...}` hinzugefügt. Jetzt ok?

2023-03-28 10:30 UTC, nrueh commented
@tortinator done

2023-03-28 18:54 UTC, tortinator approved these changes
Alles ok, bis auf das paper von @susuhahnml beim TAASP'23...

2023-03-29 14:41 UTC, tortinator approved these changes
Perfetto!

2023-03-29 14:42 UTC, merged