Wanko
krr-up/bibliography pull request #160
Opened 2023-06-01 12:56 UTC by wanko

Add local bib-entries for SI Algorithms publications

2023-06-01 17:07 UTC, tortinator requested changes
Almost done :nerd_face:

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  title = {Nurse (re) scheduling via answer set programming},
```suggestion
  title = {Nurse (re)scheduling via answer set programming},
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  publisher = {Springer Berlin Heidelberg},
```suggestion
  publisher = springer,
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  publisher = {Elsevier Morgan Kaufmann},
@string?

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  publisher = {Cambridge University Press},
@string?

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  booktitle = {In Proceedings of Forum on Specification and Design Languages (FDL'16)},
```suggestion
  booktitle = {Proceedings of Forum on Specification and Design Languages (FDL'16)},
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +(or {SMT}-based) Approaches},
```suggestion
  title = {Constraint Answer Set Programming: Integrational and Translational (or {SMT}-based) Approaches},
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  journal = {Theory and Practice of Logic Programming},
```suggestion
  journal = tplp,
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  booktitle = {Proceedings of the 13th Asia and South Pacific Design Automation Conference (ASP-DAC'08),},
```suggestion
  booktitle = {Proceedings of the thirteenth Asia and South Pacific Design Automation Conference (ASP-DAC'08),},
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  publisher = {Springer International Publishing},
```suggestion
  publisher = springer,
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  booktitle = {Workshop Methoden Und Beschreibungssprachen Zur Modellierung Und Verifikation Von Schaltungen Und Systemen},
```suggestion
  booktitle = {Workshop Methoden und Beschreibungssprachen zur Modellierung und Verifikation von Schaltungen und Systemen},
```

2023-06-01 17:07 UTC, tortinator commented on krr.bib
> +  author = {M. Thompson and A. D. Pimentel},
```suggestion
  author = {M. Thompson and A. Pimentel},
```

2023-06-13 16:15 UTC, tortinator commented
Hi @wanko , there's still work for you :innocent:

2023-06-20 10:38 UTC, wanko commented on krr.bib
> +  publisher = {IOS Press},
done

2023-06-20 10:39 UTC, wanko commented on krr.bib
> +  publisher = {Elsevier Morgan Kaufmann},
Only occurred once, so I left it.

2023-06-20 10:39 UTC, wanko commented on krr.bib
> +  publisher = {Cambridge University Press},
done

2023-06-22 06:03 UTC, tortinator requested changes
Almost there. @wanko :nerd_face:

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  year = {2023}
Are you sure, they are the same ...? One may contain more details, eg appendices than the other ...

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  booktitle = {Proceedings of the thirteenth Asia and South Pacific Design Automation Conference (ASP-DAC'08),},
```suggestion
  booktitle = {Proceedings of the Thirteenth Asia and South Pacific Design Automation Conference (ASP-DAC'08),},
```

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  booktitle = {Embedded Computer Systems: Architectures, Modeling, and Simulation},
Proceedings of ...?

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  booktitle = {Proceedings of International Conference on Embedded Computer Systems: Architectures, Modeling and Simulation (SAMOS'16)},
```suggestion
  booktitle = {Proceedings of the International Conference on Embedded Computer Systems: Architectures, Modeling and Simulation (SAMOS'16)},
```

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  booktitle = {Workshop Methoden und Beschreibungssprachen zur Modellierung und Verifikation von Schaltungen und Systemen},
Proceedings

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  booktitle = {Proceedings of IEEE Computer Society Annual Symposium on Emerging VLSI Technologies and Architectures (ISVLSI'06)},
```suggestion
  booktitle = {Proceedings of the IEEE Computer Society Annual Symposium on Emerging VLSI Technologies and Architectures (ISVLSI'06)},
```

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  title = {Exploiting domain knowledge in system-level MPSoC design space exploration},
```suggestion
  title = {Exploiting domain knowledge in system-level {MPSoC} design space exploration},
```

2023-06-22 06:03 UTC, tortinator commented on krr.bib
> +  author = {E. Zitzler and L. Thiele and M. Laumanns and C.M. Fonseca and V.G. da Fonseca},
```suggestion
  author = {E. Zitzler and L. Thiele and M. Laumanns and C. Fonseca and V. da Fonseca},
```

2023-06-22 09:52 UTC, wanko commented
@tortinator hopefully all good now :)

2023-06-22 13:04 UTC, tortinator approved these changes

2023-06-22 13:05 UTC, tortinator commented
Hi @wanko , I approved but CI failed :(

2023-06-22 18:11 UTC, wanko commented
> Hi @wanko , I approved but CI failed :(

I don't understand, I've run the script again and pushed but it still fails. Will have a closer look tomorrow.

2023-06-23 05:52 UTC, wanko commented
I did the same thing again in a fresh conda environment and now it worked. I love that we have non-deterministic technology, that makes our automata so much shorter. :D

2023-06-23 05:56 UTC, merged