add script to format authors
krr-up/bibliography pull request #180
Opened 2024-06-13 18:19 UTC by rkaminsk

2024-06-13 18:20 UTC, rkaminsk commented
@jorgefandinno and @tortinator, would you please check if the changes to the authors are okay?

2024-06-14 09:28 UTC, jorgefandinno requested changes

2024-06-14 09:28 UTC, jorgefandinno commented on procs.bib
> +  editor = {O. {de Moor} and G. Gottlob and T. Furche and S. A},
This should be "A. Sellers". It was wrongly introduced in the original file.

2024-06-14 09:32 UTC, jorgefandinno commented on procs.bib
> +  editor = {O. {de Moor} and G. Gottlob and T. Furche and S. A},
editor = {O. {de Moor} and G. Gottlob and T. Furche and A. Sellers},

2024-06-14 09:32 UTC, jorgefandinno commented on procs.bib
> +  editor = {O. {de Moor} and G. Gottlob and T. Furche and S. A},
This should be "A. Sellers". It was wrongly introduced in the original file.

2024-06-14 09:38 UTC, rkaminsk commented on procs.bib
> +  editor = {O. {de Moor} and G. Gottlob and T. Furche and S. A},
Thanks, merged your PR.

2024-06-14 09:41 UTC, rkaminsk commented
I had another quick pass and the authors look fine to me now.

2024-06-14 09:42 UTC, jorgefandinno commented on procs.bib
> +  editor = {O. {de Moor} and G. Gottlob and T. Furche and S. A},
The notes belong to a previous version. Should we describe the new version? Should we do it in a separated file or in the README.md?

2024-06-14 11:37 UTC, jorgefandinno commented
I removed it from the description the functionality that is not in the script:
- It generates BibTeX keys from the author names and the year using the
  bibliography conventions
- It replaces journal names by their corresponding BibTeX strings
- It finds crossrefs in the procs.bib file and uses them for crossref field
- It flags repeated entries
This was part of a previous script that we discussed was too long to start with. If there is interest, we can later add this back.

2024-06-14 11:40 UTC, rkaminsk commented
I made a pass over the authors and would merge now. The next step would be to include the functionality into the bibfmt.py script. We can however test the script for a while first.

2024-06-15 17:10 UTC, jorgefandinno commented
> I made a pass over the authors and would merge now. The next step would be to include the functionality into the bibfmt.py script. We can however test the script for a while first.

Sounds good. Then, we can merge as it is.

2024-06-16 08:10 UTC, merged