added papers recommanded by Son about how to represent actions
krr-up/bibliography pull request #70
Opened 2020-12-08 09:51 UTC by EtienneTignon

2020-12-08 09:54 UTC, tortinator requested changes
Merci @EtienneTignon . Please format the entries along our conventions (see `README.md`)

2021-01-05 12:39 UTC, tortinator commented
Salut @EtienneTignon : What about your pull request? @tortinator

2021-01-12 14:16 UTC, EtienneTignon commented
Hi @tortinator . Sorry for the delay. I'm still on it.

2021-01-12 14:21 UTC, tortinator commented
No worries, @EtienneTignon, I just wanted to make sure that it is not forgotten :)

2021-03-19 16:35 UTC, tortinator requested changes

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +@comment{-_-_-_-_-_-_-_-_-_-_-_-_-feb_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_}
What's this?

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +@inproceedings{basotu2002a,
2002 -> 02

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  month = {01},
delete

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +}
Where has it appeared?

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  doi = {10.3233/978-1-61499-098-7-217},
delete

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  month = {01},
delete

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +@article{cafogi2012a,
Is this an article in a journal..?

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +@inbook{cafoloda2016a,
2016  -> 16

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  abstract = {Planning in hybrid systems is important for dealing with realworldapplications. PDDL+ supports this representation ofdomains with mixed discrete and continuous dynamics, andsupports eve
delete

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  day = {12},
delete

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  language = {English},
delete

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  month = jun,
delete

2021-03-19 16:35 UTC, tortinator commented on krr.bib
> +  booktitle = {Twenty-Sixth International Conference on Automated Planning and Scheduling},
crossref via procs.bib?

2021-04-12 12:08 UTC, tortinator requested changes

2021-04-12 12:08 UTC, tortinator commented on krr.bib
> +}
compare with existing arxiv entries - this is no proper article, just a miscellaneous entry

2021-04-12 12:08 UTC, tortinator commented on krr.bib
> +
same as above

2021-04-12 12:10 UTC, tortinator commented
Your branch is now about 80 commits behind. You should merge in the current master.

2021-05-31 09:46 UTC, tortinator requested changes
This is inacceptable - you really need to get your act together!

2021-06-01 11:27 UTC, closed without merging