Dynamic Bibliography
krr-up/bibliography pull request #81
Opened 2021-04-30 15:32 UTC by susuhahnml

2021-05-01 05:39 UTC, tortinator requested changes

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +  number = {06},
What's a number in a proceeding?

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +  volume = {34},
There cannot be 34 volumes in a conference proceeding  :nerd_face:

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +  booktitle = aaai,
aaai is an organization, use a crossref to refer to a conference organzied by aaai

2021-05-01 05:39 UTC, tortinator commented on krr.bib
>  }
A good example for a bad reference but I guess this is on me, sigh!

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +
Please redo with cross reference, since kr20 should be in `procs.bib`

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +
Please redo with cross reference, since `icaps19` should be in procs.bib

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +
See above

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +
Thank you for moving it!

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +
This is already in `procs.bib`, cf `ARHandbook`

2021-05-01 05:39 UTC, tortinator commented on krr.bib
> +  title = {Planning with Different Forms of Domain-Dependent Knowledge in Answer Set Planning},
Nope, you are referring to another paper - be careful!

https://dl.acm.org/doi/10.1145/1183278.1183279

2021-05-04 00:50 UTC, susuhahnml commented on krr.bib
>  }
I dont understand. I don't remeber changing this. Should there be a reference in procs.bib for `tableaux94` and reference that?

2021-05-04 00:50 UTC, susuhahnml commented on krr.bib
> +  volume = {34},
Fixed it with the crossref

2021-05-04 00:50 UTC, susuhahnml commented on krr.bib
> +  number = {06},
Fixed it with the crossref

2021-05-04 00:50 UTC, susuhahnml commented on krr.bib
> +  title = {Planning with Different Forms of Domain-Dependent Knowledge in Answer Set Planning},
Sorry. :(

2021-05-04 01:00 UTC, susuhahnml commented on krr.bib
>  }
Perhaps in changed when I ran the format. I looked for the reference of 94 but it seams like there is not much info online. But it looks like it is the only reference anyway.

2021-05-05 12:18 UTC, tortinator requested changes
Almost perfect :nerd_face:

2021-05-05 12:18 UTC, tortinator commented on krr.bib
> -  pages = {4729--4735},
You have to keep the pages

2021-05-05 16:37 UTC, susuhahnml commented
Fixed! :)

2021-05-06 06:04 UTC, merged

2021-05-06 06:05 UTC, tortinator commented
Thx! FYI I deleted your branch