added foxlon11a and foxlon11b.
krr-up/bibliography pull request #82
Opened 2021-06-01 11:21 UTC by EtienneTignon

Sorry for the pull requests on the SonsRecommendation branch. I discussed with Javier this morning and I hope by starting anew I will do things correctly this time. If this is correct, I'll add the other papers I should.

2021-06-01 15:10 UTC, tortinator requested changes
@EtienneTignon , `arxiv` publications are only used as a transition, the ultimate paper should always be cited *if already available*

2021-06-01 15:10 UTC, tortinator commented on krr.bib
> +}
ditto https://www.jair.org/index.php/jair/article/view/10352

2021-06-14 13:40 UTC, EtienneTignon commented on krr.bib
> +}
It was removed, I found the paper somewhere else on the document.

2021-06-14 13:41 UTC, EtienneTignon commented on krr.bib
> +}
I corrected the date and linked to the definitive(?) version of the paper.
I think it should be ok now.

2021-06-15 05:48 UTC, tortinator requested changes
Why do you think page numbers and issues are irrelevant..?

2021-06-15 05:48 UTC, tortinator commented on krr.bib
> +
You miss the page numbers and the issue though

2021-06-15 10:35 UTC, EtienneTignon commented on krr.bib
> +
I didn’t knew if it was relevant. I looked at other entries and followed them.
I will add them.

2021-06-15 15:05 UTC, tortinator approved these changes

2021-06-15 15:05 UTC, merged